name: Playwright Tests

on:
  pull_request:
    branches:
      - main

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # JOB_STEPS_PLACEHOLDER
